[IS-23-24] pr_nivel1
T-ASAPP/T-asapp pull request #15
Opened 2024-02-14 16:22 UTC by AndreaMGG

listo para revisión

2024-02-14 16:30 UTC, AndreaMGG commented
@jj listo para revisión

2024-02-14 17:34 UTC, JJ commented
Corregid por favor los problemas que hay en la entrega, y luego paso a revisarlo.
También os agradecería que pasárais la lista de comprobación y la pusiérais en el cuerpo del PR

2024-02-14 19:52 UTC, JJ requested changes
Por favor, afinad un poco las historias de usuario.

2024-02-14 19:52 UTC, JJ commented on docs/hu1_perfil_usuario.md
> +HU1 - Crear un perfil de usuario personalizado con información sobre mi salud
Todas las historias de usuario tienen que incluir una *persona*.

2024-02-14 19:52 UTC, JJ commented on docs/hu1_perfil_usuario.md
> +Ojalá haya una página web en la que pueda crear un perfil de usuario personalizado que incluya información sobre mi salud, preferencias dietéticas y restricciones alimenticias para obtener recomendac
Siempre están en el dominio del problema. *Nunca* en el de las soluciones.

2024-02-14 19:52 UTC, JJ commented on docs/hu2_consultar_ recetas_personalizadas.md
> +HU2 - Consultar Recetas Personalizadas
Tenéis que secuenciar las historias de usuario de forma que tengan complejidad creciente.

2024-02-14 19:52 UTC, JJ commented on docs/hu5_opciones_para_dietas_específicas.md
> +Como usuario con necesidades dietéticas específicas (vegetariano, vegano, sin gluten, etc.), deseo tener la opción de filtrar las
Esta es la quinta ¿creéis que posiblemente sea la más simple?

2024-02-15 18:49 UTC, AndreaMGG commented
@JJ 
* [x] ¿Las historias de usuario y los milestones constituyen una guía
    suficiente para poder comenzar el desarrollo de un proyecto?
* [x] ¿Los milestones están ordenados correctamente, de forma que el 1 o
   0 sea lo primero que hay que empezar a publicar?
* [x] ¿Todos los milestones se construyen sobre el anterior, teniendo un
   orden lógico el desarrollo?
* [x] ¿El milestone 0 tiene asignada alguna historia de usuario?
* [x] ¿El milestone 0 corresponde con lo mencionado varias veces en
   clase, y en concreto con lo que se solicita en el objetivo
   siguiente?
* [x] ¿Todos los milestones describen correctamente un producto y qué
   lo hace válido, y no un  concepto vago, una funcionalidad o una tarea?
* [x] ¿Los milestones son graduales, o hay un salto grande entre ellos?
* [x] ¿Los milestones iniciales son internos, y hay a continuación milestones o
   productos externos?
* [x] ¿Los milestones son mínimos, es decir, incluyen un producto
   mínimamente viable para poder avanzar?
* [x] ¿El milestone 0 es mínimo *y* viable?
* [ ] ¿Se indica claramente cómo comprobar la viabilidad del PMV de cada hito? Es
    decir, ¿se dice qué requisitos técnicos tiene que cumplir el producto de
    cada hito?
* [ ] ¿Entre dos milestones consecutivos, no hay ningún PMV posible o por el
    contrario podrían desarrollarse muchas posibles etapas internas o externas
    de un proyecto?

2024-02-15 18:53 UTC, JJ approved these changes
👍 
Mirad a ver si necesitáis algo más para entender qué vais a hacer en el milestone 0: consultad el nivel 2 del material.

2024-02-15 18:53 UTC, JJ commented on docs/h17_alimentos_grasas.md
> +Me llamo Electronio y me gustaría saber qué alimentos son ricos en grasas.
Esto no es un problema, es una pregunta. No me preocupa mucho, porque es la 17.

2024-02-21 16:37 UTC, merged