[ISS5] Preparación
T-ASAPP/T-asapp pull request #41
Opened 2024-02-22 19:41 UTC by AndreaMGG

2024-02-26 18:03 UTC, JJ requested changes
No se ve cuál es el código. Tendrías que modificar las líneas que quieras que se revisen.

2024-02-26 18:57 UTC, JJ commented
Porfa, tomaros en serio los mensajes de commit, que *realmente* sirven para saber qué hay en el código y por qué se ha cambiado: [4847d01](https://github.com/T-ASAPP/T-asapp/pull/41/commits/4847d01f08f853c9d12fc5b28dfc3d644c77f13c)

2024-02-26 19:14 UTC, AndreaMGG commented
@JJ listo para revision (edicion de codigo issue 5 #41 )

2024-02-26 19:15 UTC, JJ commented
Por si acaso, "edición issue x" tampoco es un buen mensaje de commit. Créeme, cuando estés revisando código por cualquier cosa y quieres averiguar por qué se ha hecho para solucionar el problema lo último que quieres ver es "edición issue x"

2024-02-26 19:16 UTC, JJ approved these changes
LGTM.
Parece bastante razonable, no incluye más que lo que se pide, y parece un buen paso para seguir adelante.
Convendría de todas formas que lo revisara el resto, porque ya sabéis que los PRs sirven tanto para controlar la calidad como para transmitir conocimiento.

2024-02-27 17:48 UTC, sergiohut commented
* [x] ¿Los issues que ha planteado la persona son efectivamente problemas y
evidencian comprensión de las historias de usuario? Si no es así, es mejor que
se le transmita antes de que empiece a crear cualquier código erróneo.
* [x] ¿Has comprobado que efectivamente el compañero/a ha seguido *su* lista de
      comprobación?
* [x] ¿El código creado es una modelización válida de las historias de usuario
      creadas por ti, y te sirve como base para programar la lógica de negocio?
* [x] ¿El código creado sigue las mejores prácticas para el lenguaje de
      programación que hayáis consensuado, tanto en identificadores, como
      nombres de ficheros, como disposición de los diferentes ficheros en el
      repositorio? Por ejemplo, ¿todos los commits se refieren a un issue y
      aportan código para resolver el problema planteado en el mismo?
* [x] ¿He comprobado que el código compile, o que quien lo ha programado lo
ha hecho y documentado en el repositorio?
* [x] ¿He añadido el PR y todos los issues que se resuelvan en él al milestone
correspondiente, que será el primero?
* [x] ¿Cubre totalmente el milestone 0, o hará falta modelización adicional en
el objetivo 4 para poder programar la lógica de negocio?
* [x] En resumen, ¿considero que con lo hecho puedo ponerme a trabajar
directamente en el siguiente milestone, que incluye la lógica de negocio?

2024-03-04 19:25 UTC, sergiohut approved these changes

2024-03-04 19:37 UTC, merged