[ISS2] Ingredientes
T-ASAPP/T-asapp pull request #42
Opened 2024-02-22 19:42 UTC by Avz20

2024-02-26 18:05 UTC, JJ requested changes
Por favor, entended bien de qué se trata un modelo. No se trata nunca de valores específicos, sino de tener en cuenta todos los issues para que no sea nada incorrecto.

2024-02-26 18:05 UTC, JJ commented on models/ingredientes.py
> +carnes = {"Pollo", "Res", "Cerdo", "Pescado"}
Hay que trabajar sobre un modelo, no valores específicos.

2024-02-26 18:05 UTC, JJ commented on models/ingredientes.py
> +ingredientes = {
Igual que en las recetas tradicionales, lo que nos interesa aquí es la forma de los datos y las relaciones que hay entre sí, no los valores. En todo caso es posible que no cumpla la hU #22 sobre recetas tradicionales.

2024-02-27 13:30 UTC, JJ commented
¿Crees que "archivos actualizados" sigue las buenas prácticas en mensajes de commit?

2024-02-27 16:29 UTC, JJ requested changes
En Domain Driven Design hay (a un nivel básico) dos tipos de objetos
* Objetos valor: son inmutables, no tienen ningún tipo de ID, no varían.
* Entidades; crean y destruyen y validan objetos valor, pueden variar, incluyen lógica de negocio (las funciones)

Tenéis que distinguir entre el objeto valor para algo (como ingrediente) de las instancias de ese ingrediente cualificadas (cantidad o lo que sea) que haya en una entidad.

Esta entidad no tiene por qué tener una clase adicional para contener la cantidad (o lo que sea). Simplemente un valor al que corresponda una clave, por ejemplo.

2024-02-27 16:29 UTC, JJ commented on recipeers/ingredientes.py
> +    self.medida = medida
¿No os parece que habría que distinguir entre el objeto valor que es ingrediente y la cantidad de ingrediente que pueda haber en una receta determinada? Si no, ¿repetís cada vez que aparezca un ingrediente en una receta el nombre y la medida?

2024-02-27 17:14 UTC, JJ requested changes
¿El issue #42 hace alguna referencia a la *cantidad* de los ingredientes, o solo a *qué son* los ingredientes? Si es así, ¿por qué incluís referencias a alguna cantidad? ¿No tendrá que gestionarse eso en una receta como dice en #44 ?

2024-02-27 17:14 UTC, JJ commented on recipeers/ingredientes.py
> +        self.nombre = nombre
¿Por qué habéis quitado la medida? ¿La medida es específica de cada ingrediente o no?

2024-02-27 17:14 UTC, JJ commented on recipeers/ingredientes.py
> +        self.unidad_medida = unidad_medida
¿Diferentes cantidades van a tener diferentes medidas? ¿O la medida va a depender sólo del ingrediente?

Y en todo caso que quisiérais hacerlo así, ¿habéis oido hablar de la herencia?

(Que no estoy diciendo que lo debáis hacer así: ¿os repito lo de la entidad y objeto valor?)

2024-02-27 17:14 UTC, JJ commented on recipeers/ingredientes.py
> +    def __repr__(self):
¿Os pide esto la historia de usuario y el milestone en el que estáis?

2024-02-27 17:32 UTC, JJ commented
Todos los issues tienen que estar en el milestone en el que se esté trabajando.

2024-02-27 18:50 UTC, JJ approved these changes
👍 
Por favor, revisadlo el resto también y cuando haya suficiente número de aprobaciones, se fusiona.

2024-02-27 18:54 UTC, AndreaMGG commented
[x] ¿Los issues que ha planteado la persona son efectivamente problemas y
evidencian comprensión de las historias de usuario? Si no es así, es mejor que
se le transmita antes de que empiece a crear cualquier código erróneo.
* [x] ¿Has comprobado que efectivamente el compañero/a ha seguido *su* lista de
      comprobación?
* [x] ¿El código creado es una modelización válida de las historias de usuario
      creadas por ti, y te sirve como base para programar la lógica de negocio?
* [x] ¿El código creado sigue las mejores prácticas para el lenguaje de
      programación que hayáis consensuado, tanto en identificadores, como
      nombres de ficheros, como disposición de los diferentes ficheros en el
      repositorio? Por ejemplo, ¿todos los commits se refieren a un issue y
      aportan código para resolver el problema planteado en el mismo?
* [x] ¿He comprobado que el código compile, o que quien lo ha programado ha lo
ha hecho y documentado en el repositorio?
* [x] ¿He añadido el PR y todos los issues que se resuelvan en él al milestone
correspondiente, que será el primero?
* [x] ¿Cubre totalmente el milestone 0, o hará falta modelización adicional en
el objetivo 4 para poder programar la lógica de negocio?
* [x] En resumen, ¿considero que con lo hecho puedo ponerme a trabajar
directamente en el siguiente milestone, que incluye la lógica de negocio?

2024-02-27 18:55 UTC, JJ commented
De veras que os agradezco que me hagáis caso en esta lista de comprobación, pero 1. Va solo en #34 y 2. De veras que tenéis que darle una vuelta sobre lo que marcáis.

2024-02-27 19:17 UTC, AndreaMGG approved these changes

2024-02-27 19:18 UTC, sergiohut approved these changes

2024-02-27 19:18 UTC, merged