[ISS4] Cantidades y unidades de medida
T-ASAPP/T-asapp pull request #43
Opened 2024-02-22 19:42 UTC by tomasjpardo

2024-02-27 17:32 UTC, JJ commented
Solicitad revisión cuando esté listo.

2024-02-27 17:46 UTC, sergiohut commented
* [x] ¿Los issues que ha planteado la persona son efectivamente problemas y
evidencian comprensión de las historias de usuario? Si no es así, es mejor que
se le transmita antes de que empiece a crear cualquier código erróneo.
* [x] ¿Has comprobado que efectivamente el compañero/a ha seguido *su* lista de
      comprobación?
* [x] ¿El código creado es una modelización válida de las historias de usuario
      creadas por ti, y te sirve como base para programar la lógica de negocio?
* [x] ¿El código creado sigue las mejores prácticas para el lenguaje de
      programación que hayáis consensuado, tanto en identificadores, como
      nombres de ficheros, como disposición de los diferentes ficheros en el
      repositorio? Por ejemplo, ¿todos los commits se refieren a un issue y
      aportan código para resolver el problema planteado en el mismo?
* [x] ¿He comprobado que el código compile, o que quien lo ha programado lo
ha hecho y documentado en el repositorio?
* [x] ¿He añadido el PR y todos los issues que se resuelvan en él al milestone
correspondiente, que será el primero?
* [x] ¿Cubre totalmente el milestone 0, o hará falta modelización adicional en
el objetivo 4 para poder programar la lógica de negocio?
* [x] En resumen, ¿considero que con lo hecho puedo ponerme a trabajar
directamente en el siguiente milestone, que incluye la lógica de negocio?

2024-02-27 17:55 UTC, JJ commented
@sergio, eso va al cuerpo del PR *principal*, es decir, a #34 
Deberíais de preguntar "Por qué" de vez en cuando. El por qué va ahí es porque os sirve a vosotros para ver si habéis hecho todo lo correspondiente al nivel, y a mi también para ver si lo habéis hecho.

2024-02-27 18:02 UTC, JJ requested changes
Pensaba que se había cambiado esto como hablamos.

2024-02-27 18:02 UTC, JJ commented on Recipeers/unidades.py
> +medida = {
¿Esto no lo habías cambiado?

2024-03-01 08:51 UTC, AndreaMGG approved these changes

2024-03-04 08:55 UTC, JJ requested changes
El fichero que habéis cambiado de nombre, ¿es necesario?
Las medidas que usáis, ¿son consistentes con las "tradicionales"? ¿Es una lista exhaustiva?

2024-03-04 16:01 UTC, JJ commented
Este último commit resuelve un problema que no habéis planteado. Y por tanto es imposible saber si realmente es válido o no. Si lo habláis entre vosotros en vez de plantear el issue, al final se acaban haciendo cosas que son difíciles de evaluar (también para vosotros dentro de un tiempo)

2024-03-04 16:41 UTC, merged

2024-03-06 17:12 UTC, JJ commented
Habéis modificado esto directamente sobre la rama de este nivel sin hacer un PR. Convendría que lo hiciérais siempre, para que los PRs ejerciten su labor de control de calidad y gestión del conocimiento.