Issue 1
T-ASAPP/T-asapp pull request #44
Opened 2024-02-22 19:45 UTC by PabloES796

2024-02-26 18:06 UTC, JJ commented
Debes enlazar correctamente el issue.

2024-02-26 18:07 UTC, JJ requested changes
Aparte, ¿cómo vas a tener en cuenta si es tradicional o no según el HU1?

2024-02-26 18:07 UTC, JJ commented on models/recetas.py
> +    self.imagen = imagen
¿Esto lo pide alguna historia de usuario?

2024-02-26 18:07 UTC, JJ commented on models/recetas.py
> +    self.descripcion = descripcion
¿Esto lo pide alguna historia de usuario?

2024-02-27 17:48 UTC, sergiohut commented
* [x] ¿Los issues que ha planteado la persona son efectivamente problemas y
evidencian comprensión de las historias de usuario? Si no es así, es mejor que
se le transmita antes de que empiece a crear cualquier código erróneo.
* [x] ¿Has comprobado que efectivamente el compañero/a ha seguido *su* lista de
      comprobación?
* [x] ¿El código creado es una modelización válida de las historias de usuario
      creadas por ti, y te sirve como base para programar la lógica de negocio?
* [x] ¿El código creado sigue las mejores prácticas para el lenguaje de
      programación que hayáis consensuado, tanto en identificadores, como
      nombres de ficheros, como disposición de los diferentes ficheros en el
      repositorio? Por ejemplo, ¿todos los commits se refieren a un issue y
      aportan código para resolver el problema planteado en el mismo?
* [x] ¿He comprobado que el código compile, o que quien lo ha programado lo
ha hecho y documentado en el repositorio?
* [x] ¿He añadido el PR y todos los issues que se resuelvan en él al milestone
correspondiente, que será el primero?
* [x] ¿Cubre totalmente el milestone 0, o hará falta modelización adicional en
el objetivo 4 para poder programar la lógica de negocio?
* [x] En resumen, ¿considero que con lo hecho puedo ponerme a trabajar
directamente en el siguiente milestone, que incluye la lógica de negocio?

2024-02-27 18:27 UTC, JJ requested changes
Y avisad cuando esté listo para revisión. Por cierto, lo que cambiés en otra rama no debería afectar a esta *hasta que no lo hayáis fusionado*. Puede que todavía se cambie alguna cosa más.

2024-02-27 18:27 UTC, JJ commented on recipeers/recetas.py
> +    def __init__(self, nombre: str, listaIngredientes: List[Tuple[Ingrediente, float]], pasosPreparacion: List[Preparacion]):
Recordad que hay que incluir las definiciones de los otras clases que se usen aquí.

2024-03-05 15:14 UTC, PabloES796 reviewed
corrección de error tipográfico

2024-03-05 15:16 UTC, JJ commented
Los comentarios deben ir en los mensajes de commit; y sigues sin enlazar el issue correspondiente. Recuerda que nunca se puede trabajar con la historia de usuario, sino con issues que especifiquen diferentes problemas.

2024-03-05 15:36 UTC, maguilerafr commented
He visto que en las PRs aprobadas no habéis cerrado los issues a los que hace referencia, no se si deberíais poner "closes #numero" para que así se cierren los issues una vez se merge la PR

2024-03-05 15:40 UTC, JJ commented
Buen punto. Si lo hacéis, el cuerpo del PR una vez fusionado se incorpora como mensaje de commit. Pero si no se ha hecho antes de fusionar, debéis ponerlo en el cuerpo del PR principal.

2024-03-05 15:44 UTC, merged